# This Cloud Build configuration builds the Docker image for Tanuki-Programmer
# and deploys it to Google Cloud Run.

steps:
# Step 1: Build the Docker image
# The Dockerfile is located in the 'src' directory.
# The image will be tagged with the commit SHA and pushed to Google Container Registry (GCR).
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tanuki-programmer:$COMMIT_SHA', '.']
  dir: 'src' # Specify the directory where the Dockerfile is located

# Step 2: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tanuki-programmer:$COMMIT_SHA']

# Step 3: Deploy the image to Google Cloud Run
# This step assumes you have a Cloud Run service defined.
# Replace 'tanuki-programmer-service' with your desired service name.
# Adjust region and other parameters as needed.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'tanuki-programmer-service' # Name of your Cloud Run service
    - '--image'
    - 'gcr.io/$PROJECT_ID/tanuki-programmer:$COMMIT_SHA'
    - '--region'
    - 'us-central1' # Choose an appropriate region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated' # Adjust based on your authentication needs
    # Add any other necessary flags, e.g., --memory, --cpu, --min-instances, --max-instances
    # For example, to specify memory and CPU:
    # - '--memory=2Gi'
    # - '--cpu=2'
    # For environment variables, you can use --set-env-vars or a service.yaml file
    # - '--set-env-vars=OLLAMA_BASE_URL=http://ollama-service:11434' # Example for internal Ollama service
  env:
    - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

images:
- 'gcr.io/$PROJECT_ID/tanuki-programmer:$COMMIT_SHA'

# Optional: Define substitutions for manual triggers
# substitutions:
#   _SERVICE_NAME: tanuki-programmer-service
#   _REGION: us-central1
